<?php
$title = $this->message->getSubject();
$title = $this->escapeHtml($title);
$this->headTitle($title);

echo $this->menu_helper();
?>
<h2><?php echo $title; ?></h2>
<br/>
<div class="alert alert-info">
    <span><b><?php echo $this->translate("Sender"); ?></b>: <?php echo $this->sender ?></span><br />
    <?php if ($this->receiverCount === 1): ?>
        <span><b><?php echo $this->translate("Receiver"); ?></b>: <?php echo $this->escapeHtml($this->receiver); ?></span>
    <?php else: ?>
        <span><b><?php echo $this->translate("Receivers Count"); ?>: <?php echo $this->receiverCount; ?></b></span><br />
        <span><b><?php echo $this->translate("Receivers"); ?>: </b><?php echo $this->escapeHtml($this->receiver); ?></span><br />
    <?php endif; ?><br />
    <span>
        <?php echo $this->privateSmartTime()->fromDateTime($this->message->getCreatedDateTime()->format('l, jS F Y  h:i A')); ?>
    </span>
</div>
<div class="well">
    <?php echo $this->escapeHtml($this->message->getMessageText()); ?><br />
    <center>
        <a href="#" class="btn btn-primary btn-lg" role="button"><i class="glyphicon glyphicon-trash"></i> <?php echo $this->translate("Delete")?></a>
    </center>
</div>
