<?php
//$subTitle = "Message By " . $this->zfcUserDisplayName($sender);
$title = $message->getSubject();
$title = $this->escapeHtml($title);
$this->headTitle($title);

echo $this->menu_helper();
?>
<h2><?php echo $title; ?></h2>
<br/>
<div class="alert alert-info">
    <span><b>Sender</b> : <?php echo $this->zfcUserDisplayName($sender); ?></span>
    <span class="pull-right">
        <?php echo $messageReceiver->getSentDateTime()->format('l, jS F Y  h:i A'); ?>
    </span>
</div>
<br/>
<div class="well">
    <?php echo $this->escapeHtml($message->getMessageText()); ?>
</div>
