<?php
$title = $message->getSubject();
$title = $this->escapeHtml($title);
$this->headTitle($title);

echo $this->menu_helper();
?>
<h2><?php echo $title; ?></h2>
<br/>
<div class="alert alert-info">
    <span><b>Sender</b> : <?php echo $sender ?></span><br />
    <?php if (isset($receiver)): ?>
        <span><b>Receiver</b> : <?php echo $receiver; ?></span>
    <?php else: ?>
        <span><b>Receivers Count:<?php echo count($receivers); ?></b></span>
        <span><a href="<?php echo $this->url('privatemessaging/receivers', array('message_id' => $message->getId())); ?>">View Receivers</a></span>
    <?php endif; ?><br />
    <span class="pull-right">
        <?php echo $message->getCreatedDateTime()->format('l, jS F Y  h:i A'); ?>
    </span>
</div>
<br/>
<div class="well">
    <?php echo $this->escapeHtml($message->getMessageText()); ?>
</div>
