<?php
    $title = ucfirst($type) . " Messages";
    $title = $this->escapeHtml($title);
    $this->headTitle($title);
    $this->headScript()->appendFile($this->basePath()."/private-messaging/js/messaging.js");
    $this->headLink()->appendStylesheet($this->basePath()."/private-messaging/css/messaging.css");

    echo $this->menu_helper();
?>
<h2><?= $title ?></h2>
<br/>
<?php if ($type === 'inbox' || $type === 'unread'): ?>
    <div class="btn-group">
        <a class="btn btn-default mark-all">Mark All</a>
        <a class="btn btn-default unmark-all">Unmark All</a>
        <a class="btn btn-default read-unread" data-new-value="read">Mark as read</a>
        <a class="btn btn-default read-unread" data-new-value="unread">Mark as unread</a>
    </div>
    <br/>
    <br/>
<?php
endif;

foreach ($messages as $message): ?>
    <div class="well" data-message-id="<?php echo $message->id ?>" data-is-received="<?php echo $message->received_or_not ?>">
        <?php if ($type === 'inbox' || $type === 'unread'): ?>
            <span><label>
                    <input type='checkbox' name='mark[]' multiple='multiple' class='mark'>
                </label></span>
        <?php endif; ?>
        <span class='glyphicon  messaging-star' data-type='<?php echo $this->privateMessagingComparer()->isStarred($message) ? 'star' : 'unstar' ?>'  title=''><i class='icon-star'></i></span>
        <span class='glyphicon  messaging-imp' data-type='<?php echo $this->privateMessagingComparer()->isImportant($message) ? 'ok' : 'unok' ?>'  title=''><i class='icon-ok'></i></span>
        <span><a class="message_subject" href="<?php echo $this->url('privatemessaging/info', array('message_id' => $message->message_id)); ?>"><?php echo $message->subject ?></a></span>
        <span><?php echo $message->sender;?></span>
        <span class="pull-right"><?php echo $this->privateSmartTime()->fromDateTime($message->created_date_time); ?></span>
    </div>
<?php endforeach;

echo $this->paginationControl(
    $this->messagesOrig,
    'sliding',
    // the partial to use to render the control
    'private-messaging/partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'list',
        'type' => $this->type,
    )
);
?>
