<?php
    $title = ucfirst($type) . " Messages";
    $title = $this->escapeHtml($title);
    $this->headTitle($title);
    $this->headScript()->appendFile($this->basePath()."/private-messaging/js/messaging.js");
    $this->headLink()->appendStylesheet($this->basePath()."/private-messaging/css/messaging.css");

    echo $this->menu_helper();
?>
<h2><?= $this->translate($title) ?></h2>
<br/>
<?php if ($type === 'inbox' || $type === 'unread'): ?>
    <div class="btn-group">
        <a class="btn btn-default mark-all"><?php echo $this->translate("Mark All"); ?></a>
        <a class="btn btn-default unmark-all"><?php echo $this->translate("Unmark All"); ?></a>
        <a class="btn btn-default read-unread" data-new-value="read"><?php echo $this->translate("Mark as read"); ?></a>
        <a class="btn btn-default read-unread" data-new-value="unread"><?php echo $this->translate("Mark as unread"); ?></a>
    </div>
    <br/>
    <br/>
<?php
endif;

foreach ($messages as $message):
?>
    <div class="well" data-message-id="<?php echo $message->message_id ?>" data-is-received="<?php echo $message->received_or_not ?>">
        <?php if ($type === 'inbox' || $type === 'unread'): ?>
            <span><label>
                    <input type='checkbox' name='mark[]' multiple='multiple' class='mark'>
                </label></span>
        <?php endif;
        echo $this->privateMessagingComparer()->isStarred($message) ? "<i class='glyphicon glyphicon-star'></i>" : '';
        echo $this->privateMessagingComparer()->isImportant($message) ? "<i class='glyphicon glyphicon-ok'></i>" : '' ?>
        <span><a class="message_subject" href="<?php echo $this->url('privatemessaging/info', array('message_id' => $message->message_id)); ?>"><?php echo $this->escapeHtml($message->subject) ?></a></span>
        <span><?php echo $this->escapeHtml($message->sender);?></span>
        <span class="pull-right"><?php echo $this->privateSmartTime()->fromDateTime($message->created_date_time); ?></span>
    </div>
<?php endforeach;

echo $this->paginationControl(
    $this->messagesOrig,
    'sliding',
    // the partial to use to render the control
    'private-messaging/partial/paginator.phtml',
    // the route to link to when a user clicks a control link
    array(
        'route' => 'privatemessaging/list',
        'type' => $this->type,
    )
);
?>
