<?php
$title = $this->escapeHtml('Receivers of Message - ' . $message->getSubject());
$this->headTitle($title);

echo $this->menu_helper();
?>
<h2><?php echo $title; ?></h2>
<br/>
<table class="table">
    <tr>
        <th>S.N.</th>
        <th>Name</th>
    </tr>
    <?php foreach ($receivers as $i => $receiver): ?>
        <tr>
            <td><?php echo ($i + 1); ?></td>
            <td><?php echo $this->zfcUserDisplayName($receiver); ?></td>
        </tr>
    <?php endforeach; ?>
</table>

