<?php
$title = "Sent Messages";
$this->headTitle($title);

echo $this->menu_helper();
?>
<h2><?= $title ?></h2>
<br/>
<?php foreach ($messages as $message): ?>
    <div class="well" data-message-id="<?php echo $message->id ?>" data-is-received="<?php echo $message->received_or_not ?>">
        <span class='custom_tooltip' data-type='<?php echo $this->htMessagingComparer()->isStarred($message) ? 'star' : 'unstar' ?>'  title=''><i class='icon-star'></i></span>
        <span class='custom_tooltip' data-type='<?php echo $this->htMessagingComparer()->isImportant($message) ? 'ok' : 'unok' ?>'  title=''><i class='icon-ok'></i></span>
        <span><a class="message_subject" href="<?php echo $this->url('htmessaging/sent_info', array('message_id' => $message->id)); ?>"><?php echo $message->subject ?></a></span>
        <span class="pull-right"><?php echo $this->htSmartTime()->fromDateTime($message->created_date_time); ?></span>
    </div>
<?php endforeach; ?>